### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_ap_banner] [IOS11.2mobile] No audio for video in example box

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1104] opened 2018-01-11 00:21 UTC
No audio for video in example box in components amp_ap_banner
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp ap banner"
6.Observe no audio for the video in example box 

Observer result: No audio for video in example box
Expected result: Audio should be enabled
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MQ8D2LL/A IPhone 8
-Android OS version = 11.2.2
-Device Serial number= F2MVHJAKJCLY

![image-1](https://user-images.githubusercontent.com/35077268/34802336-08eb8700-f622-11e7-8a66-98bae8326fe0.jpg)

**Comment by kul3r4** [comment] 2018-01-11 10:54
I verified this bug and I agree the video is not playing on Firefox. I think it's a problem with amp-video and Firefox, infact also [the video sample](https://ampbyexample.com/components/amp-video/) does not work on firefox. Could you create a bug on amphtml project?

**Comment by ampff** [comment] 2018-01-12 21:39
Created in amphtml project..
https://github.com/ampproject/amphtml/issues/12823

**Comment by kul3r4** [comment] 2018-01-15 10:08
Closing this as this is not a bug on ABE. Please reopen in case the contrary is confirmed.

**Closed by kul3r4** 2018-01-15 10:08 UTC

**Comment by kul3r4** [comment] 2018-02-13 11:20
@ericlindley-g FYI
