### ISSUE TITLE
ABE Playground returns 404 in the preview frame

### ISSUE THREAD

**Issue by ymotongpoo** [ampproject/amp-by-example#857] opened 2017-06-15 12:12 UTC
On opening the [ABE Playground](https://ampbyexample.com/playground/), it shows "404 page not found" text in the preview window and it's impossible to preview the result of live editor.

By opening the page in incognito mode, it works.

The error message in the console in DevTools is the following:
```
(index):16807 GET https://ampbyexample.com/playground/playground/preview/ 404 ()
(anonymous) @ (index):16807
```

The exact line that causes error is:

```
previewIframe.src = PREVIEW_REQUEST_URL;
```

and the error message pop-up is saying

```
Failed to load resource: the server responded with a status of 404 ()
```

![2017-06-15 20 56 47](https://user-images.githubusercontent.com/145104/27180203-363c35ba-520d-11e7-86d5-73bc715416c5.png)

**Comment by kul3r4** [comment] 2017-06-16 07:34
Hi!
Is this similar to #798? Could you try the approach suggested there?

**Comment by ithinkihaveacat** [comment] 2017-06-16 08:23
Looks like this is a dupe of #798. (I've had this intermittently too.)

**Comment by ymotongpoo** [comment] 2017-06-16 10:22
It worked with clearing all cached data using DevTools.

It's all up to you but is this intended behavior? Otherwise, do we have plans to fix the SW so it can correctly upgrade the version?

**Comment by kul3r4** [comment] 2017-06-16 19:45
@ymotongpoo We don't, feel free to assign this issue to yourself if you would like working on it.

**Closed** 2017-06-30 09:41 UTC
