### ISSUE TITLE
amp-story viewer does not display on mobile

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amp-by-example#1303] opened 2018-06-07 16:46 UTC
The embedded amp story viewer disappears on mobile. This seems to effect every page that has this viewer. I don't know how many people actually read docs like this on there phone, but may be an issue.

edit: gif was too long to embed. Direct link is here: https://i.imgur.com/7tqlS7p.gifv

**Comment by sebastianbenz** [comment] 2018-07-25 10:57
This is working as intended. As you said, not sure if there is a good way to embed a story on mobile. Closing this issue for now, please reopen if you have a good idea how to to this.

**Closed by sebastianbenz** 2018-07-25 10:57 UTC
