### ISSUE TITLE
Issue with AMP Access Laterpay example code

### ISSUE THREAD

**Issue by sanketio** [ampproject/amp-by-example#1547] opened 2018-10-04 10:38 UTC
### Issue
I've been trying to use amp-access-laterpay (https://www.ampproject.org/docs/reference/components/amp-access-laterpay) but facing some issues with my setup. 

### Steps to reproduce:
1. Copy whole AMPHTML from https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-access-laterpay%2Fsource%2F without any change and paste in one HTML file.
2. Now open the HTML file in the browser and check the console. 

    ![amp-access-laterpay](https://user-images.githubusercontent.com/7807348/46468280-97a2b700-c7ed-11e8-9bb0-17203b454709.png)

    a. 412 Precondition Failed - for https://connector.sandbox.laterpaytest.net/api/v2/fetch/amp/ 
        
      ![amp-access-laterpay-412](https://user-images.githubusercontent.com/7807348/46468328-bd2fc080-c7ed-11e8-8119-24ced7aadab6.png)

    b. CORS error
    c. Authorization failed

Maybe it is a problem with Response Headers, can anyone give me any information on this.

**Comment by kul3r4** [comment] 2018-10-05 15:09
@trodrigues By looking at http://docs.laterpay.net/connector/configuring/ it seems a configuration needs to be done before using laterpay, am I correct? Could that be the reason why @sanketio cannot reproduce the sample on its own enviroment?

**Comment by pradeep910** [comment] 2018-10-10 09:00
@trodrigues @kul3r4 Thanks for the reply. 

We were hoping it to work without merchant account configuration in Sandbox mode. We'll try it and check again.

**Comment by trodrigues** [comment] 2018-10-10 09:31
The Sandbox system is just a system which doesn't use real money for testing purposes. Other than that it needs the same configurations as the Live system would need.

**Comment by trodrigues** [comment] 2018-10-10 09:31
Maybe this issue can be closed as this is not an issue with the example?

**Comment by pradeep910** [comment] 2018-10-10 14:29
Yes. We can close this. 👍

**Closed** 2018-10-10 14:30 UTC
