### ISSUE TITLE
Menu animation jank for <amp-sidebar>

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp-by-example#1240] opened 2018-04-24 18:31 UTC
This is about the examples at https://ampbyexample.com/components/amp-sidebar/ . When I try out the `<amp-sidebar>` examples by pressing a button like "Toggle Sidebar" or "Open Sidebar", the menu frequently slides out in a highly janky way. It slides over some, it stops for a fraction of a second, slides out some more, etc.

Sometimes, of course, it's fine.

I don't know if this is caused by the AMP runtime, the component, or something else, and I admit I haven't tried to debug.  It just concerns me when our menu isn't best-in-class!

**Comment by morsssss** [comment] 2018-04-24 18:32
I want to note that I don't see similar jank at https://ampstart.com/components#navigation.

**Comment by kul3r4** [comment] 2018-05-14 14:54
@morsssss I took a quick look and the problem seems to be introduced by amp-fit-text, then I found [https://github.com/ampproject/amphtml/issues/10967](https://github.com/ampproject/amphtml/issues/10967) which is related. I am closing it as it's not a bug on AMPByExample

**Closed by kul3r4** 2018-05-14 14:54 UTC

**Comment by morsssss** [comment] 2018-05-14 15:04
Hmm... this does indeed involve amp-fit-text, yes... but I'm more concerned about the janky way in which the sidebar slides in and out.

Do you see that too?

In any case, it makes sense to me that it wouldn't be a bug in ampbyexample, but something that could be improved with the component itself :)  If you'd like, I'll ask the AMP team about this instead.
